---
# tasks file for haproxy
- include: haproxypackages.yml
- name: Change config file
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy
- name: Change hosts file
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
