---
# tasks file for prestart---
- name: Set host name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}" 
- name: Install python for tools
  yum:
    name: python3
    state: latest
- name: Instal for Disable SeLinux
  yum:
    name: ['python3-libselinux', 'python3-libsemanage']
    state: latest
- name: Disable after reboot
  selinux:
    state: disabled
- name: Set SeLinux in permisive mode until next reboot
  command: setenforce 0
  ignore_errors: true
  changed_when: false
- name: Stop and disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no
